# Generated by Django 4.1.7 on 2023-03-14 05:41

from django.db import migrations, models
import django.db.models.deletion
import stock.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="カテゴリ名")),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="材料名")),
                ("value", models.IntegerField(default=0, verbose_name="値段")),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "グラム"),
                            ("p", "パック"),
                            ("lb", "LB"),
                            ("cs", "ケース"),
                            ("box", "ボックス"),
                            ("set", "セット"),
                        ],
                        max_length=255,
                        verbose_name="単位",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock.item",
                        verbose_name="カテゴリ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="親カテゴリ名")),
            ],
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.IntegerField(default=0, verbose_name="数")),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=models.SET(stock.models.get_deleted_material),
                        to="stock.material",
                        verbose_name="原材料",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_name",
                    models.CharField(
                        choices=[
                            ("penticton", "ペンティクトン店"),
                            ("west", "ウエスト"),
                            ("koya", "KOYA"),
                            ("others", "OTHERS"),
                            ("central", "セントラルキッチン"),
                        ],
                        max_length=255,
                    ),
                ),
                ("num", models.IntegerField(default=0, verbose_name="数")),
                ("date", models.DateField(help_text="作成日")),
                ("is_send", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=models.SET(stock.models.get_deleted_material),
                        to="stock.material",
                        verbose_name="原材料",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_name",
                    models.CharField(
                        choices=[
                            ("penticton", "ペンティクトン店"),
                            ("west", "ウエスト"),
                            ("koya", "KOYA"),
                            ("others", "OTHERS"),
                            ("central", "セントラルキッチン"),
                        ],
                        max_length=255,
                    ),
                ),
                ("num", models.IntegerField(default=0, verbose_name="数")),
                ("date", models.DateField(help_text="作成日")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=models.SET(stock.models.get_deleted_item),
                        to="stock.item",
                        verbose_name="アイテム",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stock.parentcategory",
                verbose_name="親カテゴリ",
            ),
        ),
        migrations.CreateModel(
            name="ShoppingHistoryProxy",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("stock.shoppinghistory",),
        ),
    ]
