# Generated by Django 4.1.7 on 2023-03-16 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="material", old_name="category", new_name="item",
        ),
    ]
