# Generated by Django 4.1.7 on 2023-03-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_warehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinghistory",
            name="is_send",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
