# Generated by Django 4.1.7 on 2023-03-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_rename_category_material_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
