# Generated by Django 4.1.7 on 2023-03-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_shoppinghistory_is_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingHistoryProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.shoppinghistory',),
        ),
        migrations.AlterField(
            model_name='shoppinghistory',
            name='is_send',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
