# Generated by Django 4.1.7 on 2023-03-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_material_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1,
                max_digits=5,
                null=True,
                verbose_name="",
            ),
        ),
    ]
