# Generated by Django 4.1.7 on 2023-03-17 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_alter_material_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1,
                max_digits=5,
                null=True,
                verbose_name="価格",
            ),
        ),
        migrations.AlterField(
            model_name="shoppinghistory",
            name="date",
            field=models.DateField(default=datetime.date.today, help_text="作成日"),
        ),
    ]
