# Generated by Django 4.1.7 on 2023-03-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_alter_material_value_alter_shoppinghistory_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.IntegerField(default=0, verbose_name="数")),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "グラム"),
                            ("p", "パック"),
                            ("lb", "LB"),
                            ("cs", "ケース"),
                            ("box", "ボックス"),
                            ("set", "セット"),
                        ],
                        max_length=255,
                        verbose_name="単位",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="material", name="item",),
        migrations.RemoveField(model_name="material", name="unit",),
        migrations.RemoveField(model_name="material", name="value",),
    ]
