# Generated by Django 4.1.7 on 2023-03-18 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0006_weight_remove_material_item_remove_material_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stock.item",
                verbose_name="カテゴリ",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="value",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                default=1,
                max_digits=12,
                null=True,
                verbose_name="価格",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="weight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stock.weight",
                verbose_name="1つ当たりの単位",
            ),
        ),
    ]
