# Generated by Django 4.1.7 on 2023-03-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0008_remove_shoppinghistory_material_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinghistory",
            name="material_unit",
            field=models.CharField(default="", max_length=255, verbose_name="材料名"),
            preserve_default=False,
        ),
    ]
