# Generated by Django 4.1.7 on 2023-03-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0009_shoppinghistory_material_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinghistory",
            name="material_unit",
            field=models.CharField(max_length=255, verbose_name="単位"),
        ),
    ]
