# Generated by Django 4.1.7 on 2023-03-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0011_alter_warehouse_num"),
    ]

    operations = [
        migrations.DeleteModel(name="Warehouse",),
    ]
