# Generated by Django 4.1.7 on 2023-03-18 04:53

from django.db import migrations, models
import stock.models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0012_delete_warehouse"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="数",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=models.SET(stock.models.get_deleted_material),
                        to="stock.material",
                        verbose_name="原材料",
                    ),
                ),
            ],
        ),
    ]
