# Generated by Django 4.1.7 on 2023-03-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0013_warehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinghistory",
            name="num",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="数",
            ),
        ),
        migrations.AlterField(
            model_name="shoppinghistory",
            name="value",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="価格",
            ),
        ),
    ]
