# Generated by Django 4.1.7 on 2023-03-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0015_alter_material_value_alter_shoppinghistory_num_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="material", name="weight",),
        migrations.AddField(
            model_name="material",
            name="unit",
            field=models.CharField(
                choices=[
                    ("g", "グラム"),
                    ("p", "パック"),
                    ("lb", "LB"),
                    ("cs", "ケース"),
                    ("box", "ボックス"),
                    ("set", "セット"),
                ],
                default="g",
                max_length=255,
                verbose_name="単位",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="Weight",),
    ]
