# Generated by Django 4.1.7 on 2023-03-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_remove_material_weight_material_unit_delete_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinghistory',
            name='material_item_name',
            field=models.CharField(default='', max_length=255, verbose_name='材料の商品名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=4, default=1, max_digits=12, null=True, verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='shoppinghistory',
            name='num',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True, verbose_name='数'),
        ),
        migrations.AlterField(
            model_name='shoppinghistory',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True, verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='num',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True, verbose_name='数'),
        ),
    ]
