# Generated by Django 4.1.7 on 2023-03-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_alter_material_value_alter_shoppinghistory_num_and_more'),
        ('stock', '0017_shoppinghistory_material_item_name_and_more'),
    ]

    operations = [
    ]
