# Generated by Django 4.1.7 on 2023-03-24 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0017_shoppinghistory_material_item_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_name",
                    models.CharField(
                        choices=[
                            ("penticton", "ペンティクトン店"),
                            ("west", "ウエスト"),
                            ("koya", "KOYA"),
                            ("warehouse", "倉庫"),
                            ("others", "OTHERS"),
                            ("central", "セントラルキッチン"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="価格",
                    ),
                ),
                (
                    "num",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="数",
                    ),
                ),
                ("material_name", models.CharField(max_length=255, verbose_name="材料名")),
                (
                    "material_item_name",
                    models.CharField(max_length=255, verbose_name="材料の商品名"),
                ),
                ("material_unit", models.CharField(max_length=255, verbose_name="単位")),
                (
                    "date",
                    models.DateField(default=datetime.date.today, help_text="作成日"),
                ),
                ("is_send", models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MaterialProxy",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("stock.material",),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="target_name",
            field=models.CharField(
                choices=[
                    ("penticton", "ペンティクトン店"),
                    ("west", "ウエスト"),
                    ("koya", "KOYA"),
                    ("warehouse", "倉庫"),
                    ("others", "OTHERS"),
                    ("central", "セントラルキッチン"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="shoppinghistory",
            name="target_name",
            field=models.CharField(
                choices=[
                    ("penticton", "ペンティクトン店"),
                    ("west", "ウエスト"),
                    ("koya", "KOYA"),
                    ("warehouse", "倉庫"),
                    ("others", "OTHERS"),
                    ("central", "セントラルキッチン"),
                ],
                max_length=255,
            ),
        ),
    ]
