# Generated by Django 4.1.7 on 2023-03-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_merge_20230320_2335'),
        ('stock', '0018_warehousehistory_materialproxy_and_more'),
    ]

    operations = [
    ]
