# Generated by Django 4.1.7 on 2023-04-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_shoppinghistory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='place',
            field=models.CharField(default='', max_length=255, verbose_name='場所名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinghistory',
            name='material_parent_category_name',
            field=models.CharField(default='', max_length=255, verbose_name='材料の親カテゴリー名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinghistory',
            name='role',
            field=models.CharField(choices=[('kitchen', 'キッチン'), ('hole', 'ホール'), ('other', 'その他')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
