# Generated by Django 4.1.7 on 2023-03-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_shoppinghistory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='place',
            field=models.CharField(default='', max_length=255, verbose_name='場所名'),
            preserve_default=False,
        ),
    ]
