# Generated by Django 4.1.7 on 2023-04-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_material_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinghistory',
            name='material_parent_category_name',
            field=models.CharField(default='', max_length=255, verbose_name='材料の親カテゴリー名'),
            preserve_default=False,
        ),
    ]
