# Generated by Django 4.1.7 on 2023-04-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_role_remove_shoppinghistory_role_material_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinghistory',
            name='role',
        ),
    ]
