# Generated by Django 4.1.7 on 2023-04-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_shoppinghistory_material_parent_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinghistory',
            name='role',
            field=models.CharField(choices=[('kitchen', 'キッチン'), ('hole', 'ホール'), ('other', 'その他')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
