# Generated by Django 4.1.7 on 2023-04-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_shoppinghistory_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='role',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('Sushi', 'Sushi'), ('dishup', 'Dish Up')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppinghistory',
            name='role',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('Sushi', 'Sushi'), ('dishup', 'Dish Up')], max_length=255),
        ),
    ]
