# Generated by Django 4.1.7 on 2023-05-09 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0024_material_extra_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinghistory',
            name='tax_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True, verbose_name='税込価格'),
        ),
    ]
