# Generated by Django 4.1.7 on 2023-04-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_role_remove_material_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='role',
            field=models.ManyToManyField(blank=True, to='stock.role'),
        ),
        migrations.AlterField(
            model_name='shoppinghistory',
            name='role',
            field=models.ManyToManyField(blank=True, to='stock.role'),
        ),
    ]
