# Generated by Django 4.1.7 on 2023-05-11 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0025_shoppinghistory_tax_value_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='shoppinghistory',
            name='tax_value',
        ),
        migrations.AddField(
            model_name='material',
            name='bottle_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ボトルの数'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_bottle_deposit',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ボトルデポジット対象か'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_drink_gst',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Drink GST対象か'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_gst',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='GST対象か'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_pst',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='PST対象か'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_recycle_fee',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='リサイクルFeeか'),
        ),
        migrations.AddField(
            model_name='shoppinghistory',
            name='bottle_deposit',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=8, null=True, verbose_name='ボトルデポジット'),
        ),
        migrations.AddField(
            model_name='shoppinghistory',
            name='drink_gst',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=8, null=True, verbose_name='Drink GST'),
        ),
        migrations.AddField(
            model_name='shoppinghistory',
            name='gst',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=8, null=True, verbose_name='GST'),
        ),
        migrations.AddField(
            model_name='shoppinghistory',
            name='pst',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=8, null=True, verbose_name='PST'),
        ),
        migrations.AddField(
            model_name='shoppinghistory',
            name='recycle_fee',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=8, null=True, verbose_name='リサイクルFee'),
        ),
    ]
