# Generated by Django 4.1.7 on 2023-05-11 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0026_remove_material_extra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliated_store', models.CharField(choices=[('penticton', 'ペンティクトン店'), ('west', 'ウエスト'), ('koya', 'KOYA'), ('warehouse', '倉庫'), ('others', 'OTHERS'), ('central', 'セントラルキッチン')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
