# Generated by Django 4.1.7 on 2023-04-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0026_alter_material_role_alter_shoppinghistory_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinghistory',
            name='material_role_name',
            field=models.CharField(default='', max_length=255, verbose_name='材のカテゴリー名'),
            preserve_default=False,
        ),
    ]
