# Generated by Django 4.1.7 on 2023-04-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0027_shoppinghistory_material_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinghistory',
            name='role',
        ),
    ]
