# Generated by Django 4.1.7 on 2023-05-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0027_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinghistory',
            name='material_position_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='材料のポジション'),
        ),
        migrations.AlterField(
            model_name='material',
            name='role',
            field=models.ManyToManyField(blank=True, to='stock.role', verbose_name='ポジション名'),
        ),
    ]
