# Generated by Django 4.1.7 on 2023-04-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0029_remove_shoppinghistory_material_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinghistory',
            name='role',
            field=models.ManyToManyField(blank=True, to='stock.role'),
        ),
    ]
