# Generated by Django 4.1.7 on 2023-04-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0030_shoppinghistory_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinghistory',
            name='role',
        ),
    ]
