# Generated by Django 4.1.7 on 2023-04-30 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_remove_shoppinghistory_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingHistory',
        ),
        migrations.DeleteModel(
            name='ShoppingHistoryProxy',
        ),
    ]
