# Generated by Django 4.1.7 on 2023-04-30 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0032_delete_shoppinghistory_delete_shoppinghistoryproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(choices=[('penticton', 'ペンティクトン店'), ('west', 'ウエスト'), ('koya', 'KOYA'), ('warehouse', '倉庫'), ('others', 'OTHERS'), ('central', 'セントラルキッチン')], max_length=255)),
                ('value', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True, verbose_name='価格')),
                ('num', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True, verbose_name='数')),
                ('material_name', models.CharField(max_length=255, verbose_name='材料名')),
                ('material_item_name', models.CharField(max_length=255, verbose_name='材料の商品名')),
                ('material_parent_category_name', models.CharField(max_length=255, verbose_name='材料の親カテゴリー名')),
                ('material_unit', models.CharField(max_length=255, verbose_name='単位')),
                ('date', models.DateField(default=datetime.date.today, help_text='注文日')),
                ('is_send', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingHistoryProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.shoppinghistory',),
        ),
    ]
