# Generated by Django 4.1.7 on 2023-05-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0034_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='価格')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='tax',
            field=models.ManyToManyField(blank=True, to='stock.tax'),
        ),
    ]
