# Generated by Django 4.1.7 on 2023-05-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0035_tax_material_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
