# Generated by Django 4.1.7 on 2023-05-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0036_tax_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='tax',
        ),
        migrations.AddField(
            model_name='material',
            name='extra',
            field=models.DecimalField(blank=True, decimal_places=4, default=1, max_digits=12, null=True, verbose_name='税金及び余分にかかる費用'),
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
