# Generated by Django 4.1.7 on 2023-05-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0038_alter_material_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='extra',
        ),
    ]
