# Generated by Django 4.1.7 on 2023-05-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0041_shoppinghistory_tax_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinghistory',
            name='tax_value',
        ),
        migrations.AddField(
            model_name='material',
            name='is_bottle_deposit',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ボトルデポジット対象か'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_drink_gst',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Drink GST対象か'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_gst',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='GST対象か'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_pst',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='PST対象か'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_recycle_fee',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='リサイクルFeeか'),
        ),
        migrations.AddField(
            model_name='shoppinghistory',
            name='bottle_deposit',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=8, null=True, verbose_name='ボトルデポジット対象'),
        ),
        migrations.AddField(
            model_name='shoppinghistory',
            name='drink_gst',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=8, null=True, verbose_name='Drink GST対象'),
        ),
        migrations.AddField(
            model_name='shoppinghistory',
            name='gst',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=8, null=True, verbose_name='GST対象'),
        ),
        migrations.AddField(
            model_name='shoppinghistory',
            name='pst',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=8, null=True, verbose_name='PST対象'),
        ),
        migrations.AddField(
            model_name='shoppinghistory',
            name='recycle_fee',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=8, null=True, verbose_name='リサイクルFee'),
        ),
    ]
