# Generated by Django 4.1.7 on 2023-05-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0042_remove_shoppinghistory_tax_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='extra',
        ),
        migrations.AddField(
            model_name='shoppinghistory',
            name='bottle_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ボトルの数'),
        ),
        migrations.AlterField(
            model_name='shoppinghistory',
            name='bottle_deposit',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=8, null=True, verbose_name='ボトルデポジット'),
        ),
        migrations.AlterField(
            model_name='shoppinghistory',
            name='drink_gst',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=8, null=True, verbose_name='Drink GST'),
        ),
        migrations.AlterField(
            model_name='shoppinghistory',
            name='gst',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=8, null=True, verbose_name='GST'),
        ),
        migrations.AlterField(
            model_name='shoppinghistory',
            name='pst',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=8, null=True, verbose_name='PST'),
        ),
    ]
