# Generated by Django 4.1.7 on 2023-05-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0043_remove_material_extra_shoppinghistory_bottle_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinghistory',
            name='bottle_num',
        ),
        migrations.AddField(
            model_name='material',
            name='bottle_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ボトルの数'),
        ),
    ]
