# Generated by Django 4.1.7 on 2023-05-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0044_remove_shoppinghistory_bottle_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinghistory',
            name='material_position_name',
            field=models.CharField(default='', max_length=255, verbose_name='材料のポジション'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='role',
            field=models.ManyToManyField(blank=True, to='stock.role', verbose_name='ポジション名'),
        ),
    ]
