# Generated by Django 4.1.7 on 2023-10-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0028_shoppinghistory_material_position_name_and_more'),
        ('stock', '0046_alter_shoppinghistory_material_position_name'),
    ]

    operations = [
    ]
