# Generated by Django 4.2.2 on 2023-11-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0047_merge_20231026_0024"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinghistory",
            name="bottle_deposit",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="ボトルデポジット",
            ),
        ),
        migrations.AlterField(
            model_name="shoppinghistory",
            name="drink_gst",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Drink GST",
            ),
        ),
        migrations.AlterField(
            model_name="shoppinghistory",
            name="gst",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="GST",
            ),
        ),
        migrations.AlterField(
            model_name="shoppinghistory",
            name="pst",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="PST",
            ),
        ),
        migrations.AlterField(
            model_name="shoppinghistory",
            name="recycle_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="リサイクルFee",
            ),
        ),
    ]
